blank_issues_enabled: true
contact_links:
  - name: Btc Igor Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Btc Igor Developers
    url: https://bitcoincore.org
    about: Btc Igor homepage
